package View;

import Control.FuncionarioControl; 
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class CadastroFuncionario extends javax.swing.JFrame { 
    
    private FuncionarioControl controlador;

    public CadastroFuncionario() {
        initComponents();
        this.controlador = new FuncionarioControl(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        c_nome_funcionario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        c_telef_funcionario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        c_cpf_funcionario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        c_rua_funcionario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        c_num_funcionario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        c_cep_funcionario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        c_ref_funcionario = new javax.swing.JTextField();
        b1_cancelar_funcionario = new javax.swing.JButton();
        b1_cadastrar_funcionario = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastramento de Funcionários");
        setMinimumSize(new java.awt.Dimension(825, 590));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Nome: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(26, 23, 40, 16);

        c_nome_funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_nome_funcionarioActionPerformed(evt);
            }
        });
        getContentPane().add(c_nome_funcionario);
        c_nome_funcionario.setBounds(26, 51, 416, 22);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Telefone: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(26, 91, 56, 16);
        getContentPane().add(c_telef_funcionario);
        c_telef_funcionario.setBounds(26, 119, 416, 22);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("CPF: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(26, 159, 26, 16);
        getContentPane().add(c_cpf_funcionario);
        c_cpf_funcionario.setBounds(26, 187, 416, 22);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Rua: ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(26, 227, 27, 16);
        getContentPane().add(c_rua_funcionario);
        c_rua_funcionario.setBounds(26, 255, 416, 22);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Número: ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(26, 295, 52, 16);
        getContentPane().add(c_num_funcionario);
        c_num_funcionario.setBounds(26, 323, 416, 22);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("CEP: ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(26, 363, 26, 16);
        getContentPane().add(c_cep_funcionario);
        c_cep_funcionario.setBounds(26, 391, 416, 22);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Referência: ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(26, 431, 67, 16);
        getContentPane().add(c_ref_funcionario);
        c_ref_funcionario.setBounds(26, 459, 416, 22);

        b1_cancelar_funcionario.setText("Cancelar");
        b1_cancelar_funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1_cancelar_funcionarioActionPerformed(evt);
            }
        });
        getContentPane().add(b1_cancelar_funcionario);
        b1_cancelar_funcionario.setBounds(436, 510, 100, 22);

        b1_cadastrar_funcionario.setText("Cadastrar");
        b1_cadastrar_funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1_cadastrar_funcionarioActionPerformed(evt);
            }
        });
        getContentPane().add(b1_cadastrar_funcionario);
        b1_cadastrar_funcionario.setBounds(560, 510, 100, 22);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/funcionarios.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(310, -40, 520, 530);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/funcionario_2.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(50, -10, 520, 530);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/branco.jpg"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(-20, -10, 860, 550);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void c_nome_funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_nome_funcionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_nome_funcionarioActionPerformed

    private void b1_cancelar_funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1_cancelar_funcionarioActionPerformed
        this.setVisible(false); 
    }//GEN-LAST:event_b1_cancelar_funcionarioActionPerformed

    private void b1_cadastrar_funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1_cadastrar_funcionarioActionPerformed
        
        try {
            
            String nome = "";
            String telefone = "";
            String cpf = "";
            String rua = "";
            int numero = 0; 
            String cep = "";
            String ref = ""; 
            
            if (this.c_nome_funcionario.getText().length() < 2) { 
                throw new Mensagens("Nome deve conter ao menos 2 caracteres.");
            } else {
                nome = this.c_nome_funcionario.getText(); 
            } 
            
            if (this.c_telef_funcionario.getText().length() < 2) { 
                throw new Mensagens("Telefone deve conter ao menos 2 numeros.");
            } else {
                telefone = this.c_telef_funcionario.getText(); 
            }
            
            if (this.c_cpf_funcionario.getText().length() < 2) { 
                throw new Mensagens("CPF deve conter ao menos 2 caracteres.");
            } else {
                cpf = this.c_cpf_funcionario.getText(); 
            }
            
            if (this.c_rua_funcionario.getText().length() < 2) { 
                throw new Mensagens("Rua deve conter ao menos 2 caracteres.");
            } else {
                rua = this.c_rua_funcionario.getText(); 
            }
            
            if (this.c_num_funcionario.getText().length() <= 0) {
                throw new Mensagens("Número da residência deve ser um número e maior que zero.");
            } else {
                numero = Integer.parseInt(this.c_num_funcionario.getText());
            } 
            
            if (this.c_cep_funcionario.getText().length() < 2) { 
                throw new Mensagens("CEP deve conter ao menos 2 caracteres.");
            } else {
                cep = this.c_cep_funcionario.getText(); 
            } 
            
            if (this.c_ref_funcionario.getText().length() < 2) { 
                throw new Mensagens("Nome deve conter ao menos 2 caracteres.");
            } else {
                ref = this.c_ref_funcionario.getText(); 
            }
            
            
            if (this.controlador.Cadastrar(cpf, rua, numero, cep, ref, nome, telefone)) {
                JOptionPane.showMessageDialog(rootPane, "Funcionário cadastrado com sucesso!");
                
                this.c_nome_funcionario.setText(""); 
                this.c_telef_funcionario.setText(""); 
                this.c_cpf_funcionario.setText(""); 
                this.c_rua_funcionario.setText(""); 
                this.c_num_funcionario.setText(""); 
                this.c_cep_funcionario.setText(""); 
                this.c_ref_funcionario.setText("");  

            } 
            
            System.out.println(this.controlador.getMinhaLista().toString()); 
            
        } catch (Mensagens erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        } catch (NumberFormatException erro2) {
            JOptionPane.showMessageDialog(null, "Informe um numero.");
        } catch (SQLException ex) {
            
        }  
    }//GEN-LAST:event_b1_cadastrar_funcionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1_cadastrar_funcionario;
    private javax.swing.JButton b1_cancelar_funcionario;
    private javax.swing.JTextField c_cep_funcionario;
    private javax.swing.JTextField c_cpf_funcionario;
    private javax.swing.JTextField c_nome_funcionario;
    private javax.swing.JTextField c_num_funcionario;
    private javax.swing.JTextField c_ref_funcionario;
    private javax.swing.JTextField c_rua_funcionario;
    private javax.swing.JTextField c_telef_funcionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
