/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.MedicoControl;
import java.sql.SQLException;
import javax.swing.JOptionPane; 

/**
 *
 * @author Juliana
 */
public class CadastroMedico extends javax.swing.JFrame {
    
    private MedicoControl control;

    public CadastroMedico() {
        initComponents();
         this.control = new MedicoControl(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        c_nome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        c_telefone = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        c_crm = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        c_especialidade = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        c_turno = new javax.swing.JTextField();
        c_cancelar = new javax.swing.JButton();
        c_cadastrar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastramento de Médicos");
        setMinimumSize(new java.awt.Dimension(750, 500));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Nome: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 34, 60, 16);
        getContentPane().add(c_nome);
        c_nome.setBounds(30, 62, 430, 22);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Telefone: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 102, 70, 16);
        getContentPane().add(c_telefone);
        c_telefone.setBounds(30, 130, 187, 22);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("CRM: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 170, 50, 16);
        getContentPane().add(c_crm);
        c_crm.setBounds(30, 198, 187, 22);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Especialidade: ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 238, 100, 16);

        c_especialidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_especialidadeActionPerformed(evt);
            }
        });
        getContentPane().add(c_especialidade);
        c_especialidade.setBounds(30, 266, 430, 22);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Turno: ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 306, 60, 16);
        getContentPane().add(c_turno);
        c_turno.setBounds(30, 334, 187, 22);

        c_cancelar.setText("Cancelar");
        c_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(c_cancelar);
        c_cancelar.setBounds(329, 408, 90, 22);

        c_cadastrar.setText("Cadastrar");
        c_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_cadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(c_cadastrar);
        c_cadastrar.setBounds(437, 408, 100, 22);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/medicos.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(250, -50, 700, 520);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/branco.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 270, 490);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void c_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_cancelarActionPerformed
         this.setVisible(false); 
    }//GEN-LAST:event_c_cancelarActionPerformed

    private void c_especialidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_especialidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_especialidadeActionPerformed

    private void c_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_cadastrarActionPerformed
       
                String nome = "";
        String telefone = "";
        String crm = "";
        String especialidade = "";
        String turno = "";

        try {

            //validando o nome 
            if (this.c_nome.getText().length() < 2) {
                //throw new vai jogar o erro para o construtor da classe Mensagens 
                throw new Mensagens("O nome deve conter ao menos 2 caracteres");
                //ao chegar no construtor da classe Mensagens, a "msg" acima entrará na variável do construtor
                //e depois o "super(msg)" vai devolver a mensagem para a classe "public Mensagens extends Exception"
            } else {
                nome = this.c_nome.getText();
            }
            //validando o telefone
            if (this.c_telefone.getText().length() <= 0) {
                throw new Mensagens("O telefone deve ser número e ser maior que zero");
            } else {
                telefone = this.c_telefone.getText();
            }
            //validando o CRM 
            if (this.c_crm.getText().length() <= 0) {
                throw new Mensagens("O CRM deve ser número e ser maior que zero");
            } else {
                crm = this.c_crm.getText();
            }
            //validando a especialidade 
            if (this.c_especialidade.getText().length() < 2) {
                throw new Mensagens("A especialidade deve conter ao menos 2 caracteres");
            } else {
                especialidade = this.c_especialidade.getText();
            }
            //validando o turno
            if (this.c_turno.getText().length() < 2) {
                throw new Mensagens("O turno deve conter ao menos 2 caracteres");
            } else {
                turno = this.c_turno.getText();
            }
            //enviando os dados validados para o MedicoControl
            if (this.control.Cadastrar(nome, crm, especialidade, turno, telefone)) {
                JOptionPane.showMessageDialog(rootPane, "O médico foi cadastrado com sucesso !");

                //agora vamos limpar os campos da Interface CadastroMedico
                this.c_nome.setText("");
                this.c_telefone.setText("");
                this.c_crm.setText("");
                this.c_especialidade.setText("");
                this.c_turno.setText("");
            }

            System.out.println(this.control.getMinhaLista().toString());
            //como a classe "public Mensagens extends Exception" tem a "msg" vamos colocar Mensagens como TIPO da variável erro
            /*erro é uma variável do tipo "msg" e este comando abaixo pode ser executado dentro do catch, 
          pois a classe Mensagens é filha (subclasse) de Exception
             */
        } catch (Mensagens erro) {
            //a variável erro sendo do tipo "msg" vai apenas pegar a "msg" no formato String e mostrá-la
            /*no caso, se uma validação der "true" e ela cair dentro deste catch, ela ficará aqui para sempre ou
              até que dê algum "false" em TRY
             */
            JOptionPane.showMessageDialog(null, erro.getMessage());

        } catch (NumberFormatException erro2) {
            JOptionPane.showMessageDialog(null, "Precisa ser um número !");

        } catch (SQLException ex) {
        } 
        
    }//GEN-LAST:event_c_cadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton c_cadastrar;
    private javax.swing.JButton c_cancelar;
    private javax.swing.JTextField c_crm;
    private javax.swing.JTextField c_especialidade;
    private javax.swing.JTextField c_nome;
    private javax.swing.JTextField c_telefone;
    private javax.swing.JTextField c_turno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
