package View;

import Control.FuncionarioControl; 
import java.sql.SQLException.*; 
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class GerenciaFuncionario extends javax.swing.JFrame {
    
    private FuncionarioControl controlador; 

    public GerenciaFuncionario() {
        initComponents();
        this.controlador = new FuncionarioControl(); 
        this.carregaTabela(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TableFuncionarios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        c2_nome_funcionario = new javax.swing.JTextField();
        b2_cancelar_funcionario = new javax.swing.JButton();
        b2_apagar_funcionario = new javax.swing.JButton();
        b2_editar_funcionario = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        c2_telef_funcionario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        c2_cpf_funcionario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        c2_rua_funcionario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        c2_num_funcionario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        c2_cep_funcionario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        c2_ref_funcionario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciamento de Funcionários");
        setMinimumSize(new java.awt.Dimension(930, 590));
        setPreferredSize(new java.awt.Dimension(950, 529));
        getContentPane().setLayout(null);

        TableFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Telefone", "CPF", "Rua", "Número", "CEP", "Referência"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableFuncionariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableFuncionarios);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 935, 225);

        jLabel1.setText("Nome: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(17, 237, 70, 16);
        getContentPane().add(c2_nome_funcionario);
        c2_nome_funcionario.setBounds(17, 265, 398, 22);

        b2_cancelar_funcionario.setText("Cancelar");
        b2_cancelar_funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2_cancelar_funcionarioActionPerformed(evt);
            }
        });
        getContentPane().add(b2_cancelar_funcionario);
        b2_cancelar_funcionario.setBounds(598, 491, 90, 22);

        b2_apagar_funcionario.setText("Apagar");
        b2_apagar_funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2_apagar_funcionarioActionPerformed(evt);
            }
        });
        getContentPane().add(b2_apagar_funcionario);
        b2_apagar_funcionario.setBounds(796, 491, 90, 22);

        b2_editar_funcionario.setText("Editar");
        b2_editar_funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2_editar_funcionarioActionPerformed(evt);
            }
        });
        getContentPane().add(b2_editar_funcionario);
        b2_editar_funcionario.setBounds(706, 491, 72, 22);

        jLabel2.setText("Telefone: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(17, 305, 60, 16);
        getContentPane().add(c2_telef_funcionario);
        c2_telef_funcionario.setBounds(17, 333, 398, 22);

        jLabel3.setText("CPF: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(17, 373, 60, 16);
        getContentPane().add(c2_cpf_funcionario);
        c2_cpf_funcionario.setBounds(17, 401, 398, 22);

        jLabel4.setText("Rua: ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(17, 441, 40, 16);
        getContentPane().add(c2_rua_funcionario);
        c2_rua_funcionario.setBounds(17, 469, 398, 22);

        jLabel5.setText("Número: ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(522, 237, 69, 16);
        getContentPane().add(c2_num_funcionario);
        c2_num_funcionario.setBounds(522, 265, 204, 22);

        jLabel6.setText("CEP: ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(522, 305, 50, 16);
        getContentPane().add(c2_cep_funcionario);
        c2_cep_funcionario.setBounds(522, 333, 204, 22);

        jLabel7.setText("Referência: ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(522, 373, 84, 16);
        getContentPane().add(c2_ref_funcionario);
        c2_ref_funcionario.setBounds(522, 401, 388, 22);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/logo.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(460, 130, 540, 570);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/branco.jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 220, 490, 350);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b2_cancelar_funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2_cancelar_funcionarioActionPerformed
        this.setVisible(false); 
    }//GEN-LAST:event_b2_cancelar_funcionarioActionPerformed

    private void TableFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableFuncionariosMouseClicked
            
        if (this.TableFuncionarios.getSelectedRow() != -1) {

            String nome = this.TableFuncionarios.getValueAt(this.TableFuncionarios.getSelectedRow(), 1).toString();
            String telefone = this.TableFuncionarios.getValueAt(this.TableFuncionarios.getSelectedRow(), 2).toString();
            String cpf = this.TableFuncionarios.getValueAt(this.TableFuncionarios.getSelectedRow(), 3).toString();
            String rua = this.TableFuncionarios.getValueAt(this.TableFuncionarios.getSelectedRow(), 4).toString();
            String numero = this.TableFuncionarios.getValueAt(this.TableFuncionarios.getSelectedRow(), 5).toString();
            String cep = this.TableFuncionarios.getValueAt(this.TableFuncionarios.getSelectedRow(), 6).toString();
            String ref = this.TableFuncionarios.getValueAt(this.TableFuncionarios.getSelectedRow(), 7).toString(); 
            
            this.c2_nome_funcionario.setText(nome);
            this.c2_telef_funcionario.setText(telefone);
            this.c2_cpf_funcionario.setText(cpf);
            this.c2_rua_funcionario.setText(rua);
            this.c2_num_funcionario.setText(numero);
            this.c2_cep_funcionario.setText(cep);
            this.c2_ref_funcionario.setText(ref); 
        }
    }//GEN-LAST:event_TableFuncionariosMouseClicked

    private void b2_editar_funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2_editar_funcionarioActionPerformed
        
        try {
            
            int id = 0; 
            String nome = "";
            String telefone = "";
            String cpf = "";
            String rua = "";
            int numero = 0; 
            String cep = "";
            String ref = ""; 
            
            if (this.c2_nome_funcionario.getText().length() < 2) { 
                throw new Mensagens("Nome deve conter ao menos 2 caracteres.");
            } else {
                nome = this.c2_nome_funcionario.getText(); 
            } 
            
            if (this.c2_telef_funcionario.getText().length() < 2) { 
                throw new Mensagens("Telefone deve conter ao menos 2 numeros.");
            } else {
                telefone = this.c2_telef_funcionario.getText(); 
            }
            
            if (this.c2_cpf_funcionario.getText().length() < 2) { 
                throw new Mensagens("CPF deve conter ao menos 2 caracteres.");
            } else {
                cpf = this.c2_cpf_funcionario.getText(); 
            }
            
            if (this.c2_rua_funcionario.getText().length() < 2) { 
                throw new Mensagens("Rua deve conter ao menos 2 caracteres.");
            } else {
                rua = this.c2_rua_funcionario.getText(); 
            }
            
            if (this.c2_num_funcionario.getText().length() <= 0) {
                throw new Mensagens("Número deve ser um número e maior que zero.");
            } else {
                numero = Integer.parseInt(this.c2_num_funcionario.getText());
            } 
            
            if (this.c2_cep_funcionario.getText().length() < 2) { 
                throw new Mensagens("CEP deve conter ao menos 2 caracteres.");
            } else {
                cep = this.c2_cep_funcionario.getText(); 
            } 
            
            if (this.c2_ref_funcionario.getText().length() < 2) { 
                throw new Mensagens("Nome deve conter ao menos 2 caracteres.");
            } else {
                ref = this.c2_ref_funcionario.getText(); 
            } 
            
            if (this.TableFuncionarios.getSelectedRow() == -1) {
                throw new Mensagens("Primeiro selecione um funcionário para editar!"); 
            } else {
                id = Integer.parseInt(this.TableFuncionarios.getValueAt(this.TableFuncionarios.getSelectedRow(), 0).toString()); 
            }
            
            if (this.controlador.Editar(cpf, rua, numero, cep, ref, id, nome, telefone)) {
                
                this.c2_nome_funcionario.setText(""); 
                this.c2_telef_funcionario.setText(""); 
                this.c2_cpf_funcionario.setText(""); 
                this.c2_rua_funcionario.setText(""); 
                this.c2_num_funcionario.setText(""); 
                this.c2_cep_funcionario.setText(""); 
                this.c2_ref_funcionario.setText(""); 
                JOptionPane.showMessageDialog(rootPane, "Funcionário editado com sucesso!"); 

            } 
            
            System.out.println(this.controlador.getMinhaLista().toString()); 
            
        } catch (Mensagens erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        } catch (NumberFormatException erro2) {
            JOptionPane.showMessageDialog(null, "Informe um número.");
        } finally {
            carregaTabela(); 
        } 
    }//GEN-LAST:event_b2_editar_funcionarioActionPerformed

    private void b2_apagar_funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2_apagar_funcionarioActionPerformed
        
            try {

            int id = 0;
            if (this.TableFuncionarios.getSelectedRow() == -1) {
                throw new Mensagens("Primeiro selecione um funcionário para APAGAR");
            } else {
                id = Integer.parseInt(this.TableFuncionarios.getValueAt(this.TableFuncionarios.getSelectedRow(), 0).toString());
            }

            int resposta_usuario = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja APAGAR este funcionário ?");

            if (resposta_usuario == 0) { 

                if (this.controlador.Apagar(id)) { 

                this.c2_nome_funcionario.setText(""); 
                this.c2_telef_funcionario.setText(""); 
                this.c2_cpf_funcionario.setText(""); 
                this.c2_rua_funcionario.setText(""); 
                this.c2_num_funcionario.setText(""); 
                this.c2_cep_funcionario.setText(""); 
                this.c2_ref_funcionario.setText(""); 
                JOptionPane.showMessageDialog(rootPane, "Funcionário apagado com sucesso!"); 

                }

            }

            System.out.println(this.controlador.getMinhaLista().toString());

        } catch (Mensagens erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        } finally { 
            carregaTabela();
        }
    }//GEN-LAST:event_b2_apagar_funcionarioActionPerformed

    /**
     * @param args the command line arguments
     */ 
    
      @SuppressWarnings("unchecked")
    public void carregaTabela() {

        DefaultTableModel modelo = (DefaultTableModel) this.TableFuncionarios.getModel(); 
        modelo.setNumRows(0);
        
        String linhasMatriz[][] = controlador.getMinhaMatrizTexto();
        for (int i = 0; i < linhasMatriz.length; i++) {
            modelo.addRow( new Object[] { 
                linhasMatriz[i][0],
                linhasMatriz[i][1],
                linhasMatriz[i][2],
                linhasMatriz[i][3],
                linhasMatriz[i][4],
                linhasMatriz[i][5],
                linhasMatriz[i][6],
                linhasMatriz[i][7], 
             }); 

        }
    } 
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciaFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableFuncionarios;
    private javax.swing.JButton b2_apagar_funcionario;
    private javax.swing.JButton b2_cancelar_funcionario;
    private javax.swing.JButton b2_editar_funcionario;
    private javax.swing.JTextField c2_cep_funcionario;
    private javax.swing.JTextField c2_cpf_funcionario;
    private javax.swing.JTextField c2_nome_funcionario;
    private javax.swing.JTextField c2_num_funcionario;
    private javax.swing.JTextField c2_ref_funcionario;
    private javax.swing.JTextField c2_rua_funcionario;
    private javax.swing.JTextField c2_telef_funcionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
